# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true

- script: |
   pwd
   git config --global user.name "sukruth"
   git config --global user.email "sukruth700@gmail.com"
   git clone https://$(TOKEN)github.com/sukruth-gms/repo-token-pem.git
   cd repo-token-pem
   cp jen-new.pem /home/vsts/work/1/s
  displayName: check