# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: 0

- script: |
   curl ifconfig.me
   echo "SONAR ANALYSIS"
   java --version
  displayName: check

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'new-sonar'
    organization: 'sonar-org-ad'
    scannerMode: 'CLI'
    configMode: 'file'
    extraProperties: |
      sonar.exclusions=**/*.css, **/*.html
      sonar.projectKey=sukruth-ms_az-pipeline-repo-test
      sonar.projectName=az-pipeline-repo-test
      sonar.verbose=true
      sonar.scanner.dumpToFile=true
      sonar.ws.timeout=300
  env:
    SONAR_SCANNER_OPTS: '-X'

- task: Maven@3
  displayName: 'Maven Build'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install sonar:sonar package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'