# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
   pwd
   git clone https://github.com/sukruth-gms/repo-token-pem.git
   cd repo-token-pem
  displayName: check