# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: 0

- script: |
   git config --global user.name "sukruth"
   git config --global user.email "sukruth700@gmail.com"
   git clone https://github.com/sukruth-gms/repo-token-pem.git
   cd repo-token-pem
   cp jen-new.pem /home/vsts/work/1/s
   ls
   ssh -i "jen-new.pem" ubuntu@ec2-3-87-12-157.compute-1.amazonaws.com
   ls
   sudo apt update
   sudo apt install fontconfig openjdk-17-jre
   java -version
   sudo wget -O /usr/share/keyrings/jenkins-keyring.asc \
   https://pkg.jenkins.io/debian/jenkins.io-2023.key
   echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
   https://pkg.jenkins.io/debian binary/ | sudo tee \
   /etc/apt/sources.list.d/jenkins.list > /dev/null
   sudo apt-get update
   sudo apt-get install jenkins
   sudo systemctl start jenkins
   sudo systemctl enable jenkins
   sudo systemctl status jenkins
   ls
   pwd
   curl ifconfig.me
  displayName: check

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'new-sonar'
    organization: 'sonar-org-ad'
    scannerMode: 'MSBuild'
    projectKey: 'sukruth-ms_az-pipeline-repo-test'
    projectName: 'az-pipeline-repo-test'
    extraProperties: |
      sonar.exclusions=**/*.css, **/*.html
      sonar.projectKey=sukruth-ms_az-pipeline-repo-test
      sonar.projectName=az-pipeline-repo-test
      timeoutSeconds: 300
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0' # Replace with the version you want to use
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'