# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
   sudo apt-get update
   sudo apt-get install maven
   mvn --version
   mvn clean
   mvn install
   mvn package
   pwd
   ls
  displayName: Building with maven