# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
   pwd
   git clone https://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@github.com/sukruth-gms/repo-token-pem.git
   cd repo-token-pem
   cp jen-new.pem /home/vsts/work/1/s
  displayName: check